In [1]:
#importing pandas library for data handling
import pandas as pd
#Dataset creation
data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}
df = pd.DataFrame(data)
# Save data as CSV file
df.to_csv("student_performance.csv", index=False)
print("CSV file created successfully!")

CSV file created successfully!

In [2]:
#Diplay first 5 rows
df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [3]:
#Display last 5 rows
df.tail()

    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

In [4]:
#Checking dataset shape
df.shape

(12, 4)

In [6]:
#column names
df.columns

Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

In [7]:
#Data types of each column
df.dtypes

Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

In [8]:
df.describe()

       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [10]:
# Features
X = df[["Study_Hours", "Attendance", "Assignments"]]

# Label
y = df["Marks"]
print("Features (X)")
print(X)
print("\nLabel (y)")
print(y)

Features (X)
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label (y)
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

# Shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (9, 3)
X_test shape: (3, 3)
y_train shape: (9,)
y_test shape: (3,)

In [13]:
#training 1st model

In [14]:
from sklearn.linear_model import LinearRegression
# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Coefficients and intercept
print("Slope (coefficients):")
print(model.coef_)

print("\nIntercept:")
print(model.intercept_)

Slope (coefficients):
[ 3.45487968  1.34491979 -2.40274064]

Intercept:
-48.100601604278054

In [15]:
#Predictions

In [16]:
# New data
new_data = pd.DataFrame({
    "Study_Hours":[5,8,12],
    "Attendance":[80,90,95],
    "Assignments":[5,8,10]
})

# Predict marks
predictions = model.predict(new_data)

print("Predicted Marks:")
print(predictions)

Predicted Marks:
[64.75367647 81.35929144 97.09792781]

In [17]:
# Predict marks for test data
y_pred = model.predict(X_test)

# Create comparison table
comparison = pd.DataFrame({
    "Actual Marks": y_test.values,
    "Predicted Marks": y_pred
})

# Calculate difference between actual and predicted
comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

# Display comparison table
print(comparison)

# Find maximum prediction error
max_error = comparison["Difference"].max()

# Display student with highest error
student = comparison[
    comparison["Difference"] == max_error
]

print("\nStudent with Highest Prediction Error:")
print(student)

   Actual Marks  Predicted Marks  Difference
0            92        92.011029    0.011029
1            88        88.269051    0.269051
2            35        31.243984    3.756016

Student with Highest Prediction Error:
   Actual Marks  Predicted Marks  Difference
2            35        31.243984    3.756016

In [18]:
# Import evaluation metrics
from sklearn.metrics import mean_absolute_error, r2_score

# Calculate Mean Absolute Error
mae = mean_absolute_error(y_test, y_pred)

# Calculate R² Score
r2 = r2_score(y_test, y_pred)

# Print results
print("Mean Absolute Error:", mae)
print("R² Score:", r2)

Mean Absolute Error: 1.3453654188948245
R² Score: 0.9929962957709836

In [19]:
#Plot Visualizations

In [20]:
pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)

In [21]:
#Study Hours VS Marks
import plotly.express as px
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)
fig.show()

In [22]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    title="Attendance vs Marks",
    hover_data=["Study_Hours", "Assignments"]
)

fig.show()

In [23]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments",
    title="Assignments vs Marks"
)

fig.show()

In [24]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line Visualization"
)

fig.show()

In [25]:
study_hours = list(range(1, 16))

prediction_df = pd.DataFrame({
    "Study_Hours": study_hours,
    "Attendance": [85]*15,
    "Assignments": [7]*15
})

trend_predictions = model.predict(prediction_df)

trend_df = pd.DataFrame({
    "Study Hours": study_hours,
    "Predicted Marks": trend_predictions
})

fig = px.line(
    trend_df,
    x="Study Hours",
    y="Predicted Marks",
    title="Predicted Marks Trend"
)

fig.show()